# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sourabh Khot
email: sourabhkhot65@gmail.com
description: >-
  Software Engineer at Tacitbase, an AI-driven recruitment software.
baseurl: ""
url: ""
github_username: sourabh-khot65
twitter_username: sourabhk65
linkedin_username: sourabhkhot65
instagram_username: sourabh_7628
photography_instagram: life.in.pixels1
company_url: https://tacitbase.com

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme settings
author:
  name: Sourabh Khot
  role: Software Engineer
  company: Tacitbase
  location: India

# Navigation
navigation:
  - title: Blog
    url: /
  - title: RSS
    url: /feed.xml

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - _script/
  - README.md
